-- Live Gold Price Chart — schema
-- Run inside Supabase SQL Editor (or via migrations)

create table if not exists public.gold_prices (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  symbol text not null default 'XAU',
  price numeric not null,
  source_updated_at timestamptz null,
  created_at timestamptz not null default now()
);

-- Prevent duplicates when the poller runs frequently:
create unique index if not exists gold_prices_ts_unique on public.gold_prices (ts);
create index if not exists gold_prices_ts_desc on public.gold_prices (ts desc);

alter table public.gold_prices enable row level security;

-- Anyone can read (chart is public).
drop policy if exists "public read gold_prices" on public.gold_prices;
create policy "public read gold_prices"
on public.gold_prices
for select
to anon, authenticated
using (true);

-- Inserts are done by Edge Function using SERVICE_ROLE (bypasses RLS).
-- If you want to allow authenticated inserts, create a separate policy.

-- Realtime (Postgres changes -> clients)
-- In Supabase Dashboard: Database -> Replication -> enable table
-- Or via SQL publication:
alter publication supabase_realtime add table public.gold_prices;
